# Generated by Django 2.2 on 2019-04-12 15:47

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(blank=True, help_text='(Item ID as obtained from the Nutritionix API)', max_length=25)),
                ('item_name', models.CharField(max_length=500)),
                ('item_image', models.ImageField(blank=True, max_length=200, null=True, upload_to=api.models.get_upload_path)),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('total_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('total_carbohydrate', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('dietary_fiber', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('sugars', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('serving_size_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('serving_size_unit', models.CharField(blank=True, max_length=300)),
                ('serving_weight_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
            ],
        ),
    ]
